name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.3.1'

      - name: Install Dependencies
        run: npm ci

      - name: Checking versions 
        run: npm version && tsc -v

      - name: Build Packages
        run: npm run prod-build
